language: ruby
gemfile:
   - test/support/chef-10.gemfile
   - test/support/chef-11.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script:
  - bundle exec foodcritic --epic-fail any ./
  - bundle exec kitchen test --parallel --log-level=info --destroy=always
